name: roche
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - seaborn
  - jupyterlab
  - rich
  - tqdm
  - scipy
  - ca-certificates
  - openssl
  - scikit-learn
  - certifi
  - ipywidgets

